// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CategoryController from "./category_controller"
application.register("category", CategoryController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import RatingController from "./rating_controller"
application.register("rating", RatingController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ShopController from "./shop_controller"
application.register("shop", ShopController)
